### ISSUE TITLE
493 decimal is octal 755

### ISSUE THREAD

**Issue by DougC** [hmrc/sbt-slug#5]
SbtDistributablesPlugin line 39 is:
`private val FILE_MODE_775 = 493`

However, 493 is octal 755, not 775, so this constant name is misleading

**Comment by SteveSmithTech** [comment]
PR please?

**Comment by DougC** [comment]
Trouble is, I don't know if the constant name is wrong, or the value, so I'm not sure which one to fix.

**Comment by SteveSmithTech** [comment]
@xnejp03 Can you help? Is the constant wrong or the value? I suspect it is the constant

**Comment by DougC** [comment]
@agilestevesmith haven't seen any response from @xnejp03 on this. Can we re-open the issue since it is unresolved?

**Comment by xnejp03** [comment]
Yes, should be 755 (ie all read, user write, all execute)

**Comment by SteveSmithTech** [comment]
@xnejp03 @DougC Can we have a PR please?

**Comment by DougC** [comment]
Grrr. Not easily. When I fork the project to my voa-govuk account I get an error:

```
[info] The config section 'remote' with subsection 'origin' had a url of 'git@github.com:voa-govuk/sbt-distributables.git'
java.net.MalformedURLException: For input string: "voa-govuk"
```

I assume this is something to do with the `sbt-git-versioning` plugin?

**Comment by DougC** [comment]
No, turns out to be a problem in `sbt-auto-build` that throws that exception. Not totally clear why, but it seems that if the `origin` url doesn't point to an HMRC repo then it blows.

Makes it impossible to fork to another github user.

**Comment by SteveSmithTech** [comment]
@DougC Could you open an issue on that library please? Thanks

**Comment by DougC** [comment]
Then you'll just ask me for a PR for that one :-)

**Comment by DougC** [comment]
Okay, I've raised https://github.com/hmrc/sbt-auto-build/issues/4

**Comment by callumcodes** [comment]
PR raised for original issue: https://github.com/hmrc/sbt-distributables/pull/11
